CREATE TABLE IF NOT EXISTS "main"."grad" ("_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "grad" VARCHAR UNIQUE );
CREATE TABLE IF NOT EXISTS "main"."pitanje" ("_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "pitanje" VARCHAR, "odgovor1" VARCHAR, "odgovor2" VARCHAR, "odgovor3" VARCHAR, "odgovor4" VARCHAR, "tacan" INTEGER, "opis" VARCHAR, "tip" INTEGER);
INSERT INTO "pitanje" VALUES(1,'Koliki procenat vode na Zemlji je slatkovodan ?','A: 50%','B: 22%','C: 3%','D: 6%',3,'Zemljina površina pokrivena je sa 74% vode, od toga 97% čini slana voda. Od preostalih 3%, 77% čini led, 22% su podzemne vode i 1% čine vode jezera,reka.... Voda je dragocena, zaista.',4);
INSERT INTO "pitanje" VALUES(2,'Voda koja je korišćena jednom ali je još uvek dovoljno čista da se ponovo koristi naziva se ?','A: Voda za višekratnu upotrebu.','B: Zelena voda','C: Sveta voda','D: Siva voda',4,'Voda iz akvarijuma, voda iz veš mašine, voda iz mašine za pranje suđa, flaširana voda koja stoji dugo, voda od tuširanja... sve se mogu ponovo koristiti .... Samo nemoj da ih prosipaš u kanalizaciju.',4);
INSERT INTO "pitanje" VALUES(3,'U proseku, koliko se vode u domaćinstvu izgubi kroz curenje ?','A: 2,9%','B: 13,7%','C: 9,3%','D: 15%',2,'Nije u svakom domaćinstvu ovaj procenat oticanja, kod nekih je i puno veći. Prvi simptom da imate curenje jeste račun koji je veći od proseka.',4);
INSERT INTO "pitanje" VALUES(4,'Koliko vode potroši prosečni vodokotlić po ispiranju ?','A: 4 litara','B: 6 litara','C: 11 litara','D: 16 litara',3,'Prosečni vodokotlić potroši 11 litara vode po ispiranju. Noviji vodokotlići troše manje a stariji više. Domaćinstvo potroši najviše vode u toaletu. Vodokotlići su posebno skloni curenju, zato prvo njih proverite.',4);
INSERT INTO "pitanje" VALUES(5,'Koliki procenat flaša od flaširane vode završava na deponijama ili u smeću ?','A: 86%','B: 93%','C:44%','D: 13%',1,'Pomnoži količinu vode u boci sa 6.74 i dobićeš količinu vode koja je potrebna za proizvodnju te boce. Na to dodaj fosilna goriva za proizvodnju, trasposrt i skladištenje ... možda smeće i nije najveći problem koji ostaje iz plastične ambalaže.',4);
INSERT INTO "pitanje" VALUES(6,'Tačno ili netačno: Ekonomičinije je da se auto pere kod kuće ?','A: Tačno','B: Netačno',NULL,NULL,2,'U većini slučaja moguće je kod kuće više uštedeti ali ne i kad se radi o pranju auta. Auto perionice danas koriste savremene aparate koji su jako mali potrošači. A ako hoćete da postupate ekološki, proverite da li Vaša auto perionica recilkira vodu.',2);
INSERT INTO "pitanje" VALUES(7,'Šta od ovoga troši najviše vode?','A: Slavina','B: tuš','C: Mašina za pranje veša',NULL,3,'Za pranje veša se u proseku koristi oko 57 litara dnevno ili 21,7 % upotrebe jednog domaćinstva, tuš čini 16 % a slavina 15,7% potrošnje domaćinstva.',3);
INSERT INTO "pitanje" VALUES(8,'Koliki procenat proizvedene
vode odlazi na zalivanje ?','A: 99%','B: 65%','C:52%','D: 70%',4,'Većina sistema za navodnjavanje ima efikasnost od samo 40 %. Zbog opterećenja koje stvara zalivanje čak se i najveća vodoizvorišta smanjuju godišenje za dva do tri metara.',4);
INSERT INTO "pitanje" VALUES(9,'Šta koristi više vode?','A: Pranje sudova ručno','B: Pranje sudova mašinski',NULL,NULL,1,'Mašinsko pranje sudova koristi za 1/6 manje vode od ručnog pranja. Ponekad je tako lako uštedeti vodu.',2);
INSERT INTO "pitanje" VALUES(10,'Koliko vode može u prosečnom domaćinstvu da se potroši za sat vremena ?','A: 3000 litara','B: 1000 litara','C:5000 litara','D: 350 litara',1,'Većina domaćinstava se vodom snabdeva preko vodomera od ¾“ koji imaju protok 3000 l/h. Nepažnjamom računi veoma brzo mogu da postnu ogromni .',4);